# Register all commands as services
services:

    UniteCMS\CoreBundle\Command\CreateDomainCommand:
        arguments: ['@doctrine.orm.default_entity_manager', '@validator', '@unite.cms.domain_definition_parser']
        tags:
            - { name: 'console.command', command: 'unite:domain:create' }

    UniteCMS\CoreBundle\Command\CreateOrganizationCommand:
        arguments: ['@doctrine.orm.default_entity_manager', '@validator']
        tags:
            - { name: 'console.command', command: 'unite:organization:create' }

    UniteCMS\CoreBundle\Command\CreatePlatformAdminCommand:
        arguments: ['@doctrine.orm.default_entity_manager', '@validator', '@security.password_encoder']
        tags:
            - { name: 'console.command', command: 'unite:user:create' }
