# Contains all core view types
services:

  # A simple table view type that renders all content documents as table rows.
  UniteCMS\CoreBundle\View\Types\TableViewType:
    tags: [unite_cms.view_type]
    public: false

  # A table view type that allows the user to sort rows via drag and drop.
  UniteCMS\CoreBundle\View\Types\SortableViewType:
    tags: [unite_cms.view_type]
    public: false
