# Contains all twig extensions.
services:

    UniteCMS\CoreBundle\Twig\AlreadyRenderedExtension:
        public: false
        tags:
            - { name: twig.extension }

    UniteCMS\CoreBundle\Twig\InstanceOfExtension:
        public: false
        tags:
            - { name: twig.extension }