imports:
  - { resource: services.core.yml }
  - { resource: services.commands.yml }
  - { resource: services.graphql.yml }
  - { resource: services.security.yml }
  - { resource: services.fieldTypes.yml }
  - { resource: services.viewTypes.yml }
  - { resource: services.validators.yml }
  - { resource: services.doctrineListener.yml }
  - { resource: services.kernelListener.yml }
  - { resource: services.serialization.yml }
  - { resource: services.twig.yml }

services:

  # This allows controller actions to inject services in the method call instead of calling $this->get('').
  UniteCMS\CoreBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']
