# Contains all doctrine event listeners.
services:

  # When removing an OrganizationMember object, also all DomainMember objects of this user must be removed.
  UniteCMS\CoreBundle\Subscriber\RemoveMember:
    public: false
    tags:
      - { name: doctrine.event_listener, event: preRemove }

  # When adding an DomainMember, also an OrganizationMember for this user and organization must be added.
  UniteCMS\CoreBundle\Subscriber\AddMember:
    public: false
    tags:
      - { name: doctrine.event_listener, event: prePersist }

  # When deleting fieldable content, remove all log entries.
  UniteCMS\CoreBundle\Subscriber\DeleteFieldableContentSubscriber:
    public: false
    tags:
      - { name: doctrine.event_listener, event: preRemove }

  # When inserting, updating or deleting content, the dispatcher notifies all parts of unite CMS about this change.
  UniteCMS\CoreBundle\Subscriber\ContentEventDispatcher:
    public: false
    arguments: ['@unite.cms.field_type_manager']
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }
      - { name: doctrine.event_listener, event: preRemove }
