# Contains all custom serialization handler
services:
  UniteCMS\CoreBundle\Field\FieldableFieldSettingsSerializationHandler:
    public: false
    tags:
      - { name: jms_serializer.handler, type: 'UniteCMS\CoreBundle\Field\FieldableFieldSettings', format: 'json', method: 'handle' }

  UniteCMS\CoreBundle\View\ViewSettingsSerializationHandler:
    public: false
    tags:
      - { name: jms_serializer.handler, type: 'UniteCMS\CoreBundle\View\ViewSettings', format: 'json', method: 'handle' }
